### ISSUE TITLE
if IE tag in Meta does not work since ie10

### ISSUE THREAD

**Issue by n3utrino** [asciidoctor/asciidoctor-backends#125]
The `<!--[if IE]>` comment should be removed. As it is no longer supported.

https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/hh801214(v=vs.85)

https://github.com/asciidoctor/asciidoctor-backends/blob/8ffcad1f9194fe2638f673aea7e41ed28c654800/slim/html5/document.html.slim#L5

**Comment by mojavelinux** [comment]
The asciidoctor-backends is woefully out of date and really shouldn't be used for anything other than a reference about how to make templates. In fact, we'll likely be archiving this project soon once we resolve https://github.com/asciidoctor/asciidoctor.org/issues/80.

**Comment by mojavelinux** [comment]
I guess we removed it from the built-in converter, so we might as well do the same here anyway.
