### ISSUE TITLE
Support vertical slides in reveal.js backend

### ISSUE THREAD

**Issue by sobkowiak** [asciidoctor/asciidoctor-backends#50]
Reveal.js provides support for vertical slides generated from subsections of the 1st level slides. Would it be possible to support this in reveal.js (if not supported yet)?

**Comment by mojavelinux** [comment]
I'm pretty sure this is resolved in the reveal.js converter. Would you agree @obilodeau?

**Comment by obilodeau** [comment]
Yes, please do. I don't have access.
