### ISSUE TITLE
Add FontAwesome support

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-backends#60]
Add FontAwesome if the value of the `icons` attribute is `font` to support font-based admonition icons and the inline icon macro.

**Comment by breskeby** [comment]
Hey Dan, any update on this issue? or is there a workaround we can use manually atm?

**Comment by cmoulliard** [comment]
The slim reveal backend could be updated easily to support that. Here is what I did with the revealjs backend in Hyla project : 

`````
https://github.com/cmoulliard/hyla/blob/master/lib/resources/backends/slim/revealjs/document.html.slim#L24-L28
    - if attr? :icons, 'font'
      - if attr? 'iconfont-remote'
        link rel='stylesheet' href=(attr 'iconfont-cdn', 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
      - else
        link rel='stylesheet' href=normalize_web_path("#{attr 'iconfont-name', 'font-awesome'}.css", (attr :revealjs_vendor_stylesdir, 'revealjs/lib/css/'))

````

**Comment by mojavelinux** [comment]
Done in the asciidoctor-reveal.js repository https://github.com/asciidoctor/asciidoctor-reveal.js/pull/25. I also fixed the HTML of admonition blocks. The icons in admonitions don't look amazing, but at least they work now :)
