### ISSUE TITLE
Problem: reveal.js backend wont generate Title slide

### ISSUE THREAD

**Issue by sappo** [asciidoctor/asciidoctor-backends#75]
asciidoctor: 1.5.1 (latest from gem)
asciidoctor-backends: cloned from master 07.10.14
reveal.js: cloned from master 07.10.14

**Comment by obilodeau** [comment]
Reveal has been split in a separate repository: https://github.com/asciidoctor/asciidoctor-reveal.js/. I would advise to close this issue and re-open it on the other repo if the behavior you are currently getting doesn't match what you expect.

**Comment by mojavelinux** [comment]
I agree this is closed.
